### ISSUE TITLE
Lonely MTL at top of output

### ISSUE THREAD

**Issue by thejohnhoffer** [aranega/simple-python-gen#1]
I've forked this master branch, as well as the tests branch, but either way I get something like this:

```python
org.eclipse.uml2.uml.internal.impl.ClassImpl@58ae45ba (name: Query, visibility: <unset>) (isLeaf: false, isAbstract: false, isFinalSpecialization: false) (isActive: false)org.eclipse.uml2.uml.internal.impl.ClassImpl@229be1e2 (name: Cache, visibility: <unset>) (isLeaf: false, isAbstract: false, isFinalSpecialization: false) (isActive: false)org.eclipse.uml2.uml.internal.impl.ClassImpl@7b7c2312 (name: Core, visibility: <unset>) (isLeaf: false, isAbstract: false, isFinalSpecialization: false) (isActive: false)org.eclipse.uml2.uml.internal.impl.ClassImpl@58ae45ba (name: Query, visibility: <unset>) (isLeaf: false, isAbstract: false, isFinalSpecialization: false) (isActive: false)org.eclipse.uml2.uml.internal.impl.ClassImpl@229be1e2 (name: Cache, visibility: <unset>) (isLeaf: false, isAbstract: false, isFinalSpecialization: false) (isActive: false)org.eclipse.uml2.uml.internal.impl.ClassImpl@7b7c2312 (name: Core, visibility: <unset>) (isLeaf: false, isAbstract: false, isFinalSpecialization: false) (isActive: false)
class Query(object):
        def __init__(self,*args,**kwargs):
                pass
        # Start of user code -> properties/constructors for Query class
```

This long one-line string (apparently some residual mtl) is always at the top of my code in all files for all classes with these custom generators. This problem occurs whether I use either branch on this fork or on Ximo's fork. This problem does not occur with either of the built-in python generators on genmymodel.com.

**Comment by aranega** [comment]
Indeed, it looks like a lonely MTL statement somewhere, however, I didn't succeed to reproduce your issue.  I tried in GenMyModel using either the custom generator modal or the embedded MTL editor with the scripts from the master branch. Could you tell me which way you are using for code generation?

**Comment by thejohnhoffer** [comment]
![](http://img.hoff.in/issues/mtl_0.png)
![](http://img.hoff.in/issues/mtl_1.png)
![](http://img.hoff.in/issues/mtl_2.png)
![](http://img.hoff.in/issues/mtl_3.png)

**Comment by thejohnhoffer** [comment]
I'm sorry- I thought my master branch was an exact copy of yours when I last tried this (before I tried to merge from XImo's branch), but I also can't reproduce this error when linking directly to your repository.

I only get this error for my fork, not your master branch. So it's not your problem!

**Comment by thejohnhoffer** [comment]
But now that I double check, adding an 'aranega' branch on my fork that is exactly up to date with your master branch now produces no errors. It looks like I was mistaken and still running Ximo's fork when I thought I was running your master branch. Apologies for wasting your time. 

Your master branch works perfectly!

**Comment by aranega** [comment]
Hey, do not worry, thank you anyway for reporting, I could have introduced a mistake one of the commit and never be aware of it (between multiple versions of the Python generator it is sometimes hard to know where you are).

If you see problematic points or improvements that could be made, feel free to offer pull requests!

Also, I saw that you used the 'custom generator' from git and also the embedded editor / generator from GenMyModel. This is probably best if you choose one way or the other (preferably the embedded editor/generator version which is faster and allows you to have preview).
